### ISSUE TITLE
ID_Token returned doesn't authenticate with API calls

### ISSUE THREAD

**Issue by TravisLRiffle** [Azure-Samples/active-directory-b2c-dotnetcore-webapi#26]
I get a 401 unauthorized when I try to call my API built from this code.  I (login) to get a id_token, but I am wondering if this should be an "access_token" or if the id_token will suffice.  Like to hear your thoughts.

**Comment by jennyf19** [comment]
@TravisLRiffle The id_token is for the client (web app) and has claims about the user. You need to use the access token with the protected resource (web API). that's why you're getting unauthorized.
Try this newer [web app calls web api with b2c sample](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C)...appologies for not seeing this question sooner.
cc: @jmprieur

**Comment by jmprieur** [comment]
Closing as this sample is being archived in favor of a better sample
